### ISSUE TITLE
Performance On KCU1500 with SDx Environment

### ISSUE THREAD

**Issue by yuanm2** [doonny/PipeCNN#98]
We successfully execute the PipeCNN's Alexnet model and here is our performance summary for testing first 10 images from imagenet. We notice that the coreConv kernel takes 339.24ms on average and macPool 521.841ms. Does anyone have the similar results?

[performance_sdx.pdf](https://github.com/doonny/PipeCNN/files/2630314/performance_sdx.pdf)

**Comment by doonny** [comment]
Anyone has optimization suggestions for Xilinx FPGAs ?

**Comment by cococener** [comment]
orry,I have a question,I want to know if this project can be compiled by SDAccel ,Because when I compiled it ,it can't produce .xclbin,I used HW and System mode,just don't have the .xclbin,and also build finished.

**Comment by cococener** [comment]
My

> We successfully execute the PipeCNN's Alexnet model and here is our performance summary for testing first 10 images from imagenet. We notice that the coreConv kernel takes 339.24ms on average and macPool 521.841ms. Does anyone have the similar results?
> 
> [performance_sdx.pdf](https://github.com/doonny/PipeCNN/files/2630314/performance_sdx.pdf)
Sorry,I have a question,I want to know if this project can be compiled by SDAccel ,Because when I compiled it ,it can't produce .xclbin,I used HW and System mode,just don't have the .xclbin,and also build finished.And if you can ,can you tell me what change do you do for the pipe project,Because my board is KCU1500,too.
